workflows:
  flutter_app_deploy:
    name: Flutter Build + Firebase Deploy
    environment:
      flutter: stable
      vars:
        FIREBASE_PROJECT_ID: "your-project-id"
    scripts:
      - flutter pub get
      - flutter build web
      - npm install -g firebase-tools
      - firebase deploy --only hosting --token \$FIREBASE_TOKEN --project \$FIREBASE_PROJECT_ID
    artifacts:
      - build/web/**/*